### ISSUE TITLE
Set up contribution guidelines/workflows

### ISSUE THREAD

**Issue by JesseTG** [angelabair/ARS327#1]
I want to ensure that we're all not stepping on each other's toes.  Pushing to `master` haphazardly is a big no-no.

**Comment by angelabair** [comment]
Just set up a branch for everyone and merge the later on. We can deal with the merge errors later.

**Comment by JesseTG** [comment]
One branch per feature, not per person.  The longer a branch exists, the more likely there will be a merge conflict.

**Comment by khouriousgeorge** [comment]
![image](https://cloud.githubusercontent.com/assets/18527852/18481101/fa543012-79a8-11e6-8d82-f3029d6a0a76.png)

**Comment by angelabair** [comment]
This is an art class. We really don't need to care about best practices.

**Comment by khouriousgeorge** [comment]
yolo

**Comment by JesseTG** [comment]
@angelabair I'm sorry, but I disagree.  Past experience has taught me that failing to adopt a good workflow is a great way to lose code, duplicate work, create lots of merge conflicts, and generally lose any idea of what's actually going on.  These problems can all be traced back to a lack of organization and discipline, and are not inherently specific to web design.

I also want to clarify that I'm not trying to dictate _what_ we're making.  I'm all for letting the site evolve naturally.  I'd just rather spend my time making something great than resolving merge conflicts.
